config/routes.rb
Myapp::Application.routes.draw do
  

 get 'signup', :to => 'users#new', :as => 'signup'
get 'login', :to => 'sessions#new', :as => 'login'
get 'logout', :to => 'sessions#destroy', :as => 'logout'

resources :users
resources :sessions

  resources :articles do
    resources :comments
  end

  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/work"
  match 'welcome/index' => 'welcome#email' , :via => :post

   root :to => 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :post, :title
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
  has_and_belongs_to_many :users

  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :body, :commenter
end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
attr_accessible :email, :password, :password_confirmation  
validates_uniqueness_of :email
has_and_belongs_to_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

def authorize
  redirect_to login_url, :alert=> "Not authorized" if current_user.nil?
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment])
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Email or password is invalid"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    session[:user_id] = @user.id
    redirect_to root_url, :notice => "Thank you for signing up!"
  else
    render "new"
  end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @articles = Article.all
  	respond_to do |format|
      format.js
      format.html
    end
  end
  
  def email
    p params

    redirect_to :back
  end
  
  def about
  	respond_to do |format|
      format.js
      format.html
    end
  end
  def contact
  	respond_to do |format|
      format.js
      format.html
    end
  end
  def work
  	respond_to do |format|
      format.js
      format.html
    end
  end

  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<section id="right">
    <header id="header-small">
    <h2>Editing The Article </h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><a href="#">Editing Article</a></h2>
    </header>
    <div class="entry">


<%= render 'form' %>

<%= link_to 'Show', @article, :class => "btn btn-small" %> 
<%= link_to 'Back', articles_path,:class => "btn btn-small" %>
    
    </div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work in Progress!!</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/articles/index.html.erb
<section id="right">
    <header id="header-small">
    <h2>List of All the Articles on website </h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><a href="#">My Articles</a></h2>
    </header>
    <div class="entry">
    
<table class ="article_table">
  <tr>
    <th>Title</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.post %></td>
    <td><%= button_to 'Show', article ,:class => "btn btn-small" %></td>
    <td><%= button_to 'Edit', edit_article_path(article) ,:class => "btn btn-small" %></td>
    <td><%= button_to 'Destroy', article, :method => :delete,:class => "btn btn-small", :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path, :class =>"btn btn-primary" %>
    
    </div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work in Progress!!</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/articles/new.html.erb
<section id="right">
    <header id="header-small">
    <h2>Create your New Article !! </h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><a href="#">New Article</a></h2>
    </header>
    <div class="entry">


<%= render 'form' %>

<%= link_to 'Back', articles_path, :class => "btn btn-small" %>
    
    </div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work in Progress!!</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/articles/show.html.erb
<section id="right">
    <header id="header-small">
    <h2>Showing Article </h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><%= @article.title %></h2>
    </header>
    <div class="entry">

<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @article.post.html_safe %>
</p>
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  <%= button_to 'Remove Comment', [comment.article, comment],:class => "btn btn-primary btn-small",
               :method => :delete,
               :data => { :confirm => 'Are you sure?' } %>
</p>
<% end %>
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit :class => "btn btn-primary" %>
  </p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article), :class => "btn btn-small" %> 
<%= link_to 'Back', articles_path , :class => "btn btn-small"%>
    </div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work in Progress!!</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyAddicted</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.8.19/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
<meta charset="UTF-8" />

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if IE 6]>
<script src="js/belatedPNG.js"></script>
<script>
	DD_belatedPNG.fix('*');
</script>
<![endif]-->

</head>
<body>
<div id="wrap">
<section id="left">
	<header id="mainheader">
	<img src="/assets/logo.jpg" width="250" height="120" alt="CleanRed | Free CSS Template"> 
    <h1 id="sitename">Welcome!!</h1>
    <div class ="logger">
    <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log Out", logout_path %>
    <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
    <% end %>
    </div>
    </header>
    <nav id="mainnav">
		<ul>
        	<li class ="current"><%=link_to "Home",welcome_index_path %></li>
            <li><%=link_to "My Work",welcome_work_path %></li>
            <li><%=link_to "About",welcome_about_path %></li>
            <li><%=link_to "Contact",welcome_contact_path %></li>
        </ul>
	</nav>


	<div id="search">
    	<form action="#">
        <div id="searchfield"><input type="text" name="search" id="s"></div>
      	<div id="searchbtn"><input type="image" src="/assets/searchgobtn.png" alt="search"></div>
        </form>
	</div>
    
    <section id="sidebar">
    <div class="sb-block">
        <%= link_to 'Add your own Article', new_article_path, :class =>"btn btn-primary" %>
    </div>
    
    <div class="sb-block">
    <h2>Categories</h2>
    <ul>
    	<li><a href="#">Web Design</a></li>
		<li><a href="#">Computers</a></li>
		<li><a href="#">Gadgets</a></li>
		<li><a href="#">CSS Templates</a></li>
		<li><a href="#">Graphics Design</a></li>
		<li><a href="#">Photography</a></li>
		<li><a href="#">General</a></li>
    </ul>
    </div>
    
    
    
    <div id="sociallinks"> <a href="#"><img src="/assets/fb-icon.jpg" width="33" height="32" alt="facebook"></a> <a href="#"><img src="/assets/twt-icon.jpg" width="33" height="32" alt="twitter"></a> <a href="#"><img src="/assets/flkr-icon.jpg" width="33" height="32" alt="flickr"></a> <a href="#"><img src="/assets/be-icon.jpg" width="33" height="32" alt="behance"></a> </div>
    </section>
</section>

<%= yield %>

<div class="clear"></div>
</div>
<footer id="pagefooter">

<div id="footerwrap">

<div id="about">

<h2>About</h2>
<div class="myphoto">


  <img src="/assets/mypic.png" width="120" height="130" alt="your photo"></div>
<div class="about-text">
<p>
I am a Web User Interface designer and Ruby On Rails Developer with passion for art, photography and web standards. I make clean, smart & usable websites
<a href="#"> Read More </a></p>

</div>
</div>
<div id="services">
<h2>Services</h2>
<ul>

	<li>Website &amp; UI design</li>
	<li>WordPress Themes</li>
	<li>Custom CSS Templates</li>
	<li>PSD to HTML / CSS</li>
	<li>Graphics Design</li>
	<li>Web Development</li>
</ul>
</div>
<div id="tools">
<h2>Expertise</h2>
<ul>

	<li>Clean, Accessible &amp; Usable Web Designs.</li>
    <li>HTML, XHTML, HTML5, CSS3 &amp; jQuery</li>
    <li>Developing Custom WordPress Themes</li>
    <li>Graphics Design</li>
    <li>Web Development</li>
    <li>Web Standards</li>
</ul>
</div>
<div class="clear"></div>
</div>
<div id="credits">
2013 &copy; Arpit Kulshrestha | Web Developer  | Developed By RubyAddicted </div>
</footer>
</body>
</html>

app/views/users/new.html.erb
<section id="right">
    <header id="header-small">
    <h2>Make your Own Website or Share With Us</h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><a href="#">Sign Up</a></h2>
    </header>
    <div class="entry">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up",:class => "btn btn-primary" %></div>
<% end %>
    
</div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work in Progress!!</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/welcome/about.html.erb
<section id="right">
	
    <header id="header-small">
    <h2>About </h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><a href="#">I am a web designer</a></h2>
    </header>
    <div class="entry">
    
    </div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work in Progress!!</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/welcome/contact.html.erb
<section id="right">
  
    <header id="header-small">
    <h2>Contact Us </h2>
   </header>
  <div class="clear"></div>
  
    <section id="contents">
    <section id="homemain">
    <article class="post singlepost">
    <header>
    <h2><a href="#">I am a web designer</a></h2>
    </header>
    <div class="entry">
    
    
    </div>
    </article></section>
    
    
    <aside id="rightsidebar">
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="165" alt="rain">
    <p class="caption">Work In Progress</p>
    </div>
    </aside>
    <div class="clear"></div>
  </section>
</section>

app/views/welcome/index.html.erb
<section id="right">
	<header id="pageheader">
   		<div id="intro">
        	<div id="introwrap">
            <h2>Hello there, Work is Still in progress! </h2>
            <p>I am a Web User Interface designer and Ruby On Rails Developer with passion for art, photography and web standards. I make clean, smart & usable websites. If you need a website, <a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal">Lets Talk</a></p>
            </div>
                    <a href="http://in.linkedin.com/pub/arpit-kulshrestha/5b/39/aa2" target= "_blank" class="resume">Linkedin</a>

        </div>
    </header>
    
    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>  
<script src="/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-modal.js"></script>

           <!-- Button to trigger modal -->
    
     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Please Provide Your Requirements</h3>
    </div>
    <div class="modal-body">
    <%= form_for welcome_index_path(@email), :method => :post do |f| %>

    <div class="field">
    <%= f.label " Your Email Address" %><br />
    <%= f.text_field :email %>
    </div>
    <div class="email">
    <%= f.label "Your Requirement" %><br />
    <%= f.text_area :details %>
    </div>
    
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>
    </div>
    <% end %>

    <section id="contents">
    <section id="homemain">
    <% @articles.each do |article| %>
    <article class="post">
    <header>
    <h2><%= link_to "#{article.title}", article_path(article.id) %></h2>
    <span class="articlemeta">Posted on <%= article.created_at %> under <a href="#">Category</a></span>
    
    </header>
    <div class="entry">
    
    <p><%= article.post.first(200).html_safe %><%= link_to "  Read more", article_path(article.id) %></p>
    
    </div>
    </article>
    <% end %>
    
    
    <a href="#"><img src="/assets/viewmorebtn.jpg" width="135" height="36" alt="view more"></a>
    </section>
    <section id="photos">
    <h2 class="subhead">Photoblog</h2>
    <div class="imagepost">
    <img src="/assets/rain.jpg" width="170" height="113" alt="rain">
    <p class="caption"><a href="#">It Rained Last Night</a></p>
    </div>
    
    <div class="imagepost">
    <img src="/assets/guitar.jpg" width="170" height="113" alt="rain">
    <p class="caption"><a href="#">It Rained Last Night</a></p>
    </div>
    
    <div class="imagepost">
    <img src="/assets/bandw.jpg" width="170" height="113" alt="rain">
    <p class="caption"><a href="#">It Rained Last Night</a></p>
    </div>
    <a href="photo.html"><img src="/assets/viewmorebtn.jpg" width="135" height="36" alt="view more"></a> </section>
    
    <div class="clear"></div>
    </section>
</section>

app/views/welcome/work.html.erb
<section id="right">
	<header id="header-small">
    <h2>Selected Works</h2>
   </header>
  <div class="clear"></div>
    <section id="contents">
    <article class="pfitem">
    <div class="pfthumb">
    <img src="/assets/ramblingsoul.jpg" width="440" height="230" alt="web design and development - ramblingsoul.com"></div>
    <div class="pfdetails">
    <h3><span class="sitename">RamblingSoul.com</span>
    Works : Website Design, HTML, CSS Coding, jQuery, WordPress Themes, Search Engine Optimization &amp; CSS Templates 
    	
    </h3>
    <p> <a href="#">Preview Work</a></p>
    </div>
    <div class="clear"></div>
    </article>
    
    
    <article class="pfitem">
    <div class="pfthumb">
    <img src="/assets/cssheaven.jpg" width="440" height="230" alt="web design and development - ramblingsoul.com"></div>
    <div class="pfdetails">
    <h3><span class="sitename">RamblingSoul.com</span>
    Works : Website Design, HTML, CSS Coding, jQuery, WordPress Themes, Search Engine Optimization &amp; CSS Templates 
    	
    </h3>
    <p> <a href="#">Preview Work</a></p>
    </div>
    <div class="clear"></div>
    </article>
    
    <article class="pfitem">
    <div class="pfthumb">
    <img src="/assets/ramblingsoul.jpg" width="440" height="230" alt="web design and development - ramblingsoul.com"></div>
    <div class="pfdetails">
    <h3><span class="sitename">RamblingSoul.com</span>
    Works : Website Design, HTML, CSS Coding, jQuery, WordPress Themes, Search Engine Optimization &amp; CSS Templates 
    	
    </h3>
    <p> <a href="#">Preview Work</a></p>
    </div>
    <div class="clear"></div>
    </article>
    
    <article class="pfitem">
    <div class="pfthumb">
    <img src="/assets/cssheaven.jpg" width="440" height="230" alt="web design and development - ramblingsoul.com"></div>
    <div class="pfdetails">
    <h3><span class="sitename">RamblingSoul.com</span>
    Works : Website Design, HTML, CSS Coding, jQuery, WordPress Themes, Search Engine Optimization &amp; CSS Templates 
    	
    </h3>
    <p> <a href="#">Preview Work</a></p>
    </div>
    <div class="clear"></div>
    </article>
    <div class="clear"></div>
    </section>
</section>